CREATE TABLE IF NOT EXISTS schema_migrations (
  version VARCHAR(100) PRIMARY KEY,
  applied_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tournaments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  edition VARCHAR(50) NOT NULL,
  slug VARCHAR(100) NOT NULL,
  host_countries JSON NOT NULL,
  starts_at DATE NOT NULL,
  ends_at DATE NOT NULL,
  team_count SMALLINT UNSIGNED NOT NULL,
  match_count SMALLINT UNSIGNED NOT NULL,
  status VARCHAR(20) NOT NULL,
  rules JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_tournaments_slug (slug),
  KEY idx_tournaments_status (status),
  CONSTRAINT chk_tournaments_status CHECK (status IN ('draft', 'upcoming', 'active', 'completed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE stages (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  tournament_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(50) NOT NULL,
  code VARCHAR(30) NOT NULL,
  stage_type VARCHAR(20) NOT NULL,
  sequence SMALLINT UNSIGNED NOT NULL,
  starts_at DATETIME(3) NULL,
  ends_at DATETIME(3) NULL,
  status VARCHAR(20) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_stages_tournament_code (tournament_id, code),
  UNIQUE KEY uq_stages_tournament_sequence (tournament_id, sequence),
  CONSTRAINT fk_stages_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE RESTRICT,
  CONSTRAINT chk_stages_type CHECK (stage_type IN ('group', 'knockout')),
  CONSTRAINT chk_stages_status CHECK (status IN ('upcoming', 'active', 'completed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tournament_groups (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  tournament_id BIGINT UNSIGNED NOT NULL,
  stage_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(30) NOT NULL,
  code VARCHAR(10) NOT NULL,
  sequence SMALLINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_groups_tournament_code (tournament_id, code),
  CONSTRAINT fk_groups_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE RESTRICT,
  CONSTRAINT fk_groups_stage FOREIGN KEY (stage_id) REFERENCES stages(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE teams (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  short_name VARCHAR(50) NOT NULL,
  code CHAR(3) NOT NULL,
  country_code VARCHAR(10) NOT NULL,
  confederation VARCHAR(20) NOT NULL,
  flag_url TEXT NULL,
  logo_url TEXT NULL,
  fifa_ranking SMALLINT UNSIGNED NULL,
  elo_rating DECIMAL(8,2) NULL,
  coach_name VARCHAR(100) NULL,
  metadata JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_teams_code (code),
  KEY idx_teams_confederation (confederation)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tournament_teams (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  tournament_id BIGINT UNSIGNED NOT NULL,
  team_id BIGINT UNSIGNED NOT NULL,
  group_id BIGINT UNSIGNED NULL,
  pot_number SMALLINT UNSIGNED NULL,
  qualification_method VARCHAR(100) NULL,
  is_host TINYINT(1) NOT NULL DEFAULT 0,
  final_position SMALLINT UNSIGNED NULL,
  eliminated_stage_id BIGINT UNSIGNED NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'qualified',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_tournament_teams (tournament_id, team_id),
  KEY idx_tournament_teams_group (group_id),
  KEY idx_tournament_teams_status (status),
  CONSTRAINT fk_tournament_teams_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE RESTRICT,
  CONSTRAINT fk_tournament_teams_team FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE RESTRICT,
  CONSTRAINT fk_tournament_teams_group FOREIGN KEY (group_id) REFERENCES tournament_groups(id) ON DELETE RESTRICT,
  CONSTRAINT fk_tournament_teams_eliminated_stage FOREIGN KEY (eliminated_stage_id) REFERENCES stages(id) ON DELETE RESTRICT,
  CONSTRAINT chk_tournament_teams_status CHECK (status IN ('qualified', 'active', 'eliminated', 'withdrawn'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE matches (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  tournament_id BIGINT UNSIGNED NOT NULL,
  stage_id BIGINT UNSIGNED NOT NULL,
  group_id BIGINT UNSIGNED NULL,
  external_id VARCHAR(100) NULL,
  match_number SMALLINT UNSIGNED NOT NULL,
  home_team_id BIGINT UNSIGNED NULL,
  away_team_id BIGINT UNSIGNED NULL,
  home_placeholder VARCHAR(100) NULL,
  away_placeholder VARCHAR(100) NULL,
  venue_name VARCHAR(150) NULL,
  host_city VARCHAR(100) NULL,
  scheduled_at DATETIME(3) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'scheduled',
  home_score_90 SMALLINT UNSIGNED NULL,
  away_score_90 SMALLINT UNSIGNED NULL,
  home_score_after_extra_time SMALLINT UNSIGNED NULL,
  away_score_after_extra_time SMALLINT UNSIGNED NULL,
  home_penalty_score SMALLINT UNSIGNED NULL,
  away_penalty_score SMALLINT UNSIGNED NULL,
  winner_team_id BIGINT UNSIGNED NULL,
  result_type VARCHAR(20) NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  source_updated_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_matches_tournament_number (tournament_id, match_number),
  UNIQUE KEY uq_matches_external_id (external_id),
  KEY idx_matches_scheduled_at (scheduled_at),
  KEY idx_matches_status (status),
  KEY idx_matches_stage (stage_id),
  CONSTRAINT fk_matches_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE RESTRICT,
  CONSTRAINT fk_matches_stage FOREIGN KEY (stage_id) REFERENCES stages(id) ON DELETE RESTRICT,
  CONSTRAINT fk_matches_group FOREIGN KEY (group_id) REFERENCES tournament_groups(id) ON DELETE RESTRICT,
  CONSTRAINT fk_matches_home_team FOREIGN KEY (home_team_id) REFERENCES teams(id) ON DELETE RESTRICT,
  CONSTRAINT fk_matches_away_team FOREIGN KEY (away_team_id) REFERENCES teams(id) ON DELETE RESTRICT,
  CONSTRAINT fk_matches_winner_team FOREIGN KEY (winner_team_id) REFERENCES teams(id) ON DELETE RESTRICT,
  CONSTRAINT chk_matches_status CHECK (status IN ('scheduled', 'live', 'finished', 'postponed', 'cancelled')),
  CONSTRAINT chk_matches_result_type CHECK (result_type IS NULL OR result_type IN ('regular_time', 'extra_time', 'penalties')),
  CONSTRAINT chk_matches_distinct_teams CHECK (home_team_id IS NULL OR away_team_id IS NULL OR home_team_id <> away_team_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE ai_models (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  provider VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  model_key VARCHAR(150) NOT NULL,
  version VARCHAR(100) NOT NULL,
  slug VARCHAR(120) NOT NULL,
  gateway VARCHAR(30) NOT NULL DEFAULT 'openrouter',
  description TEXT NULL,
  avatar_url TEXT NULL,
  personality VARCHAR(100) NULL,
  is_reasoning_enabled TINYINT(1) NOT NULL DEFAULT 0,
  reasoning_effort VARCHAR(20) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  retired_at DATETIME(3) NULL,
  metadata JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_ai_models_slug (slug),
  UNIQUE KEY uq_ai_models_provider_key_version (provider, model_key, version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE model_configs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ai_model_id BIGINT UNSIGNED NOT NULL,
  tournament_id BIGINT UNSIGNED NOT NULL,
  version INT UNSIGNED NOT NULL,
  temperature DECIMAL(4,3) NULL,
  top_p DECIMAL(4,3) NULL,
  max_output_tokens INT UNSIGNED NULL,
  seed INT NULL,
  config JSON NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 0,
  active_tournament_id BIGINT UNSIGNED GENERATED ALWAYS AS (IF(is_active = 1, tournament_id, NULL)) STORED,
  published_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_model_configs_version (ai_model_id, tournament_id, version),
  UNIQUE KEY uq_model_configs_active (ai_model_id, active_tournament_id),
  CONSTRAINT fk_model_configs_model FOREIGN KEY (ai_model_id) REFERENCES ai_models(id) ON DELETE RESTRICT,
  CONSTRAINT fk_model_configs_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE prompt_versions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  tournament_id BIGINT UNSIGNED NOT NULL,
  prompt_type VARCHAR(30) NOT NULL,
  name VARCHAR(100) NOT NULL,
  version INT UNSIGNED NOT NULL,
  version_key VARCHAR(100) NOT NULL,
  system_prompt LONGTEXT NOT NULL,
  user_prompt_template LONGTEXT NOT NULL,
  output_json_schema JSON NOT NULL,
  schema_version VARCHAR(30) NOT NULL,
  change_summary TEXT NULL,
  change_reason TEXT NULL,
  content_hash CHAR(64) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  published_at DATETIME(3) NULL,
  retired_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_prompt_versions_number (tournament_id, prompt_type, version),
  UNIQUE KEY uq_prompt_versions_key (version_key),
  UNIQUE KEY uq_prompt_versions_hash (tournament_id, prompt_type, content_hash),
  CONSTRAINT fk_prompt_versions_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE RESTRICT,
  CONSTRAINT chk_prompt_versions_type CHECK (prompt_type IN ('match', 'tournament_podium')),
  CONSTRAINT chk_prompt_versions_status CHECK (status IN ('draft', 'published', 'retired'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE match_prompt_versions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  match_id BIGINT UNSIGNED NOT NULL,
  prompt_version_id BIGINT UNSIGNED NOT NULL,
  assignment_version INT UNSIGNED NOT NULL,
  data_snapshot JSON NOT NULL,
  data_snapshot_hash CHAR(64) NOT NULL,
  data_cutoff_at DATETIME(3) NOT NULL,
  assigned_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  locked_at DATETIME(3) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'assigned',
  is_current TINYINT(1) NOT NULL DEFAULT 1,
  current_match_id BIGINT UNSIGNED GENERATED ALWAYS AS (IF(is_current = 1, match_id, NULL)) STORED,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_match_prompt_assignment (match_id, assignment_version),
  UNIQUE KEY uq_match_prompt_current (current_match_id),
  CONSTRAINT fk_match_prompt_match FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE RESTRICT,
  CONSTRAINT fk_match_prompt_version FOREIGN KEY (prompt_version_id) REFERENCES prompt_versions(id) ON DELETE RESTRICT,
  CONSTRAINT chk_match_prompt_status CHECK (status IN ('assigned', 'locked', 'voided', 'superseded'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE prediction_runs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  model_config_id BIGINT UNSIGNED NOT NULL,
  prompt_version_id BIGINT UNSIGNED NOT NULL,
  match_prompt_version_id BIGINT UNSIGNED NULL,
  match_id BIGINT UNSIGNED NULL,
  prediction_type VARCHAR(30) NOT NULL,
  idempotency_key VARCHAR(150) NOT NULL,
  gateway VARCHAR(30) NOT NULL DEFAULT 'openrouter',
  gateway_request_id VARCHAR(150) NULL,
  requested_model_key VARCHAR(150) NOT NULL,
  resolved_model_key VARCHAR(150) NULL,
  rendered_system_prompt LONGTEXT NOT NULL,
  rendered_user_prompt LONGTEXT NOT NULL,
  data_snapshot_hash CHAR(64) NOT NULL,
  request_payload JSON NOT NULL,
  raw_response JSON NULL,
  status VARCHAR(20) NOT NULL,
  attempt_number SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  input_tokens INT UNSIGNED NULL,
  output_tokens INT UNSIGNED NULL,
  cost_amount DECIMAL(12,6) NULL,
  cost_currency CHAR(3) NULL,
  latency_ms INT UNSIGNED NULL,
  error_code VARCHAR(100) NULL,
  error_message TEXT NULL,
  started_at DATETIME(3) NOT NULL,
  finished_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_prediction_runs_idempotency (idempotency_key),
  UNIQUE KEY uq_prediction_runs_gateway_request (gateway_request_id),
  KEY idx_prediction_runs_model_config (model_config_id),
  KEY idx_prediction_runs_prompt (prompt_version_id),
  KEY idx_prediction_runs_match (match_id),
  KEY idx_prediction_runs_status (status),
  CONSTRAINT fk_prediction_runs_model_config FOREIGN KEY (model_config_id) REFERENCES model_configs(id) ON DELETE RESTRICT,
  CONSTRAINT fk_prediction_runs_prompt FOREIGN KEY (prompt_version_id) REFERENCES prompt_versions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_prediction_runs_match_prompt FOREIGN KEY (match_prompt_version_id) REFERENCES match_prompt_versions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_prediction_runs_match FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE RESTRICT,
  CONSTRAINT chk_prediction_runs_type CHECK (prediction_type IN ('match', 'tournament_podium')),
  CONSTRAINT chk_prediction_runs_status CHECK (status IN ('pending', 'running', 'succeeded', 'failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE predictions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  tournament_id BIGINT UNSIGNED NOT NULL,
  match_id BIGINT UNSIGNED NOT NULL,
  ai_model_id BIGINT UNSIGNED NOT NULL,
  model_config_id BIGINT UNSIGNED NOT NULL,
  prediction_run_id BIGINT UNSIGNED NOT NULL,
  predicted_result VARCHAR(10) NOT NULL,
  predicted_home_score SMALLINT UNSIGNED NOT NULL,
  predicted_away_score SMALLINT UNSIGNED NOT NULL,
  predicted_goal_diff SMALLINT NOT NULL,
  predicted_winner_team_id BIGINT UNSIGNED NULL,
  predicted_decision_method VARCHAR(20) NULL,
  home_win_probability DECIMAL(5,4) NOT NULL,
  draw_probability DECIMAL(5,4) NOT NULL,
  away_win_probability DECIMAL(5,4) NOT NULL,
  confidence DECIMAL(5,4) NULL,
  reasoning TEXT NOT NULL,
  highlight_quote TEXT NULL,
  key_factors JSON NULL,
  uncertainties JSON NULL,
  predicted_at DATETIME(3) NOT NULL,
  locked_at DATETIME(3) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'published',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_predictions_match_model (match_id, ai_model_id),
  UNIQUE KEY uq_predictions_run (prediction_run_id),
  KEY idx_predictions_model (ai_model_id),
  CONSTRAINT fk_predictions_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE RESTRICT,
  CONSTRAINT fk_predictions_match FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE RESTRICT,
  CONSTRAINT fk_predictions_model FOREIGN KEY (ai_model_id) REFERENCES ai_models(id) ON DELETE RESTRICT,
  CONSTRAINT fk_predictions_model_config FOREIGN KEY (model_config_id) REFERENCES model_configs(id) ON DELETE RESTRICT,
  CONSTRAINT fk_predictions_run FOREIGN KEY (prediction_run_id) REFERENCES prediction_runs(id) ON DELETE RESTRICT,
  CONSTRAINT fk_predictions_winner FOREIGN KEY (predicted_winner_team_id) REFERENCES teams(id) ON DELETE RESTRICT,
  CONSTRAINT chk_predictions_result CHECK (predicted_result IN ('home', 'draw', 'away')),
  CONSTRAINT chk_predictions_decision CHECK (predicted_decision_method IS NULL OR predicted_decision_method IN ('regular_time', 'extra_time', 'penalties')),
  CONSTRAINT chk_predictions_status CHECK (status IN ('draft', 'published', 'voided'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tournament_predictions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  tournament_id BIGINT UNSIGNED NOT NULL,
  ai_model_id BIGINT UNSIGNED NOT NULL,
  model_config_id BIGINT UNSIGNED NOT NULL,
  prediction_run_id BIGINT UNSIGNED NOT NULL,
  prompt_version_id BIGINT UNSIGNED NOT NULL,
  champion_team_id BIGINT UNSIGNED NOT NULL,
  runner_up_team_id BIGINT UNSIGNED NOT NULL,
  third_place_team_id BIGINT UNSIGNED NOT NULL,
  reasoning TEXT NOT NULL,
  highlight_quote TEXT NULL,
  predicted_at DATETIME(3) NOT NULL,
  locked_at DATETIME(3) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'published',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_tournament_predictions_model (tournament_id, ai_model_id),
  CONSTRAINT fk_tournament_predictions_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE RESTRICT,
  CONSTRAINT fk_tournament_predictions_model FOREIGN KEY (ai_model_id) REFERENCES ai_models(id) ON DELETE RESTRICT,
  CONSTRAINT fk_tournament_predictions_config FOREIGN KEY (model_config_id) REFERENCES model_configs(id) ON DELETE RESTRICT,
  CONSTRAINT fk_tournament_predictions_run FOREIGN KEY (prediction_run_id) REFERENCES prediction_runs(id) ON DELETE RESTRICT,
  CONSTRAINT fk_tournament_predictions_prompt FOREIGN KEY (prompt_version_id) REFERENCES prompt_versions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_tournament_predictions_champion FOREIGN KEY (champion_team_id) REFERENCES teams(id) ON DELETE RESTRICT,
  CONSTRAINT fk_tournament_predictions_runner_up FOREIGN KEY (runner_up_team_id) REFERENCES teams(id) ON DELETE RESTRICT,
  CONSTRAINT fk_tournament_predictions_third FOREIGN KEY (third_place_team_id) REFERENCES teams(id) ON DELETE RESTRICT,
  CONSTRAINT chk_tournament_predictions_distinct CHECK (
    champion_team_id <> runner_up_team_id
    AND champion_team_id <> third_place_team_id
    AND runner_up_team_id <> third_place_team_id
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE scoring_rules (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  tournament_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  prediction_type VARCHAR(30) NOT NULL,
  points DECIMAL(8,2) NOT NULL,
  priority SMALLINT UNSIGNED NOT NULL,
  is_stackable TINYINT(1) NOT NULL DEFAULT 1,
  conditions JSON NULL,
  effective_from DATETIME(3) NOT NULL,
  effective_to DATETIME(3) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_scoring_rules_version (tournament_id, code, effective_from),
  KEY idx_scoring_rules_active (tournament_id, is_active),
  CONSTRAINT fk_scoring_rules_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE prediction_scores (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  prediction_id BIGINT UNSIGNED NULL,
  tournament_prediction_id BIGINT UNSIGNED NULL,
  scoring_rule_id BIGINT UNSIGNED NOT NULL,
  ai_model_id BIGINT UNSIGNED NOT NULL,
  match_id BIGINT UNSIGNED NULL,
  points DECIMAL(8,2) NOT NULL,
  is_hit TINYINT(1) NOT NULL,
  calculation_detail JSON NOT NULL,
  idempotency_key VARCHAR(150) NOT NULL,
  calculated_at DATETIME(3) NOT NULL,
  calculation_version INT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_prediction_scores_idempotency (idempotency_key),
  UNIQUE KEY uq_prediction_scores_match_rule (prediction_id, scoring_rule_id),
  UNIQUE KEY uq_prediction_scores_tournament_rule (tournament_prediction_id, scoring_rule_id),
  KEY idx_prediction_scores_model (ai_model_id),
  KEY idx_prediction_scores_match (match_id),
  CONSTRAINT fk_prediction_scores_prediction FOREIGN KEY (prediction_id) REFERENCES predictions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_prediction_scores_tournament_prediction FOREIGN KEY (tournament_prediction_id) REFERENCES tournament_predictions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_prediction_scores_rule FOREIGN KEY (scoring_rule_id) REFERENCES scoring_rules(id) ON DELETE RESTRICT,
  CONSTRAINT fk_prediction_scores_model FOREIGN KEY (ai_model_id) REFERENCES ai_models(id) ON DELETE RESTRICT,
  CONSTRAINT fk_prediction_scores_match FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE RESTRICT,
  CONSTRAINT chk_prediction_scores_target CHECK (
    (prediction_id IS NOT NULL AND tournament_prediction_id IS NULL)
    OR (prediction_id IS NULL AND tournament_prediction_id IS NOT NULL)
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE job_runs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  job_name VARCHAR(100) NOT NULL,
  trigger_type VARCHAR(20) NOT NULL,
  idempotency_key VARCHAR(150) NOT NULL,
  status VARCHAR(20) NOT NULL,
  input JSON NULL,
  result JSON NULL,
  error_message TEXT NULL,
  started_at DATETIME(3) NOT NULL,
  finished_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_job_runs_idempotency (idempotency_key),
  KEY idx_job_runs_name_started (job_name, started_at),
  CONSTRAINT chk_job_runs_trigger CHECK (trigger_type IN ('cron', 'manual', 'api')),
  CONSTRAINT chk_job_runs_status CHECK (status IN ('running', 'succeeded', 'failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
